-- AlterTable
ALTER TABLE `game` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `genre` ENUM('ACAO', 'AVENTURA', 'RPG', 'ESTRATEGIA', 'SIMULACAO', 'ESPORTES', 'CORRIDA', 'PUZZLE', 'TERROR', 'OUTRO') NOT NULL DEFAULT 'OUTRO';
